
import { supabase } from "@/integrations/supabase/client";
import { Case, CasePriority, CaseStatus, CaseType } from "@/types/case";

// This interface matches the actual structure in the Supabase "Cases Management" table
export interface SupabaseCase {
  "Case ID": string | null;
  Description: string | null;
  "Incident Date": string | null;
  Location: string | null;
  Priority: string | null;
  Status: string | null;
  Type: string | null;
  id?: string; // This might be auto-generated by Supabase
}

// Helper function to convert from Supabase format to our app's Case format
export const mapSupabaseCaseToAppCase = (supabaseCase: SupabaseCase): Case => {
  return {
    id: supabaseCase.id || crypto.randomUUID(), // Use provided ID or generate one
    caseId: supabaseCase["Case ID"] || "",
    description: supabaseCase.Description || "",
    incidentDate: supabaseCase["Incident Date"] || "",
    incidentTime: "", // Not directly available in Supabase structure
    location: supabaseCase.Location || "",
    unitNumber: "", // Not directly available in Supabase structure
    village: "", // Not directly available in Supabase structure
    priority: (supabaseCase.Priority?.toLowerCase() || "medium") as CasePriority,
    caseType: (supabaseCase.Type?.toLowerCase() || "other") as CaseType,
    status: (supabaseCase.Status?.toLowerCase() || "new") as CaseStatus,
    operatorName: "", // Not directly available in Supabase structure
    receivedAt: "", // Not directly available in Supabase structure
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
};

// Helper function to convert from our app's Case format to Supabase format
export const mapAppCaseToSupabaseCase = (appCase: Case): SupabaseCase => {
  return {
    id: appCase.id,
    "Case ID": appCase.caseId,
    Description: appCase.description,
    "Incident Date": appCase.incidentDate,
    Location: appCase.location,
    Priority: appCase.priority,
    Status: appCase.status,
    Type: appCase.caseType,
  };
};

// Case functions
export const getAllCases = async (): Promise<Case[]> => {
  const { data, error } = await supabase
    .from('Cases Management')
    .select('*');
  
  if (error) {
    console.error("Error fetching cases:", error);
    throw error;
  }
  
  // Convert Supabase format to our app's Case format with proper type casting
  const cases = (data || []) as unknown as SupabaseCase[];
  return cases.map(mapSupabaseCaseToAppCase);
};

export const getCaseById = async (id: string): Promise<Case | null> => {
  const { data, error } = await supabase
    .from('Cases Management')
    .select('*')
    .eq('id', id)
    .single();
  
  if (error) {
    if (error.code === 'PGRST116') { // Not found error code
      return null;
    }
    console.error("Error fetching case:", error);
    throw error;
  }
  
  // Convert Supabase format to our app's Case format using an explicit cast
  return data ? mapSupabaseCaseToAppCase(data as unknown as SupabaseCase) : null;
};

export const saveCase = async (caseData: Case): Promise<Case> => {
  // Convert app Case to Supabase format
  const supabaseCase = mapAppCaseToSupabaseCase(caseData);

  const { data, error } = await supabase
    .from('Cases Management')
    .upsert([supabaseCase])
    .select()
    .single();
  
  if (error) {
    console.error("Error saving case:", error);
    throw error;
  }
  
  // Convert back to app format with explicit casting
  return mapSupabaseCaseToAppCase(data as unknown as SupabaseCase);
};

export const createCase = async (caseData: Omit<Case, 'id'>): Promise<Case> => {
  // Generate a UUID client-side for better UX (avoid waiting for server response)
  const newCaseId = crypto.randomUUID();
  const caseIdNumber = Math.floor(10000 + Math.random() * 90000);
  
  const newCase: Case = {
    ...caseData,
    id: newCaseId,
    caseId: `CG-${caseIdNumber}`
  };
  
  // Convert app Case to Supabase format
  const supabaseCase = mapAppCaseToSupabaseCase(newCase);
  
  const { data, error } = await supabase
    .from('Cases Management')
    .insert([supabaseCase])
    .select()
    .single();
  
  if (error) {
    console.error("Error creating case:", error);
    throw error;
  }
  
  // Convert back to app format using the explicit type casting
  return mapSupabaseCaseToAppCase(data as unknown as SupabaseCase);
};

export const deleteCase = async (id: string): Promise<boolean> => {
  const { error } = await supabase
    .from('Cases Management')
    .delete()
    .eq('id', id);
  
  if (error) {
    console.error("Error deleting case:", error);
    throw error;
  }
  
  return true;
};
