// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqkikmpdmsmzmgiymhio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxa2lrbXBkbXNtem1naXltaGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzU2MDMsImV4cCI6MjA2MDcxMTYwM30.AW8o5XklVoQH-YkyI_rJLklUqnAHke-PWz6ZTo_H7Xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);